# Generated by Django 5.1.2 on 2026-04-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
    ]
